### ISSUE TITLE
Unable to run New-AzurePIMRequest to set role

### ISSUE THREAD

**Issue by bokkoman** [janegilring/PIMTools#9]
I am trying to enable a resource role 'Owner'.
But I get the following error each time:

```
PS C:\Users\REDACTED> New-AzurePIMRequest -RoleName Owner -ResourceName 'Resource Name' -ResourceType Subscription
Get-AzureADMSPrivilegedRoleDefinition: C:\Users\REDACTED\REDACTED\Documents\PowerShell\Modules\PIMTools\0.7.0\Functions\New-AzurePIMRequest.ps1:119
Line |
 119 |  … efinition -ProviderId azureResources -ResourceId $resource.Id -Filter …
     |                                                     ~~~~~~~~~~~~
     | Cannot bind argument to parameter 'ResourceId' because it is null.
PIM elevation for user REDACTED@REDACTED.onmicrosoft.com failed: Cannot bind argument to parameter 'ResourceId' because it is null.
```

Any help is appreciated.

**Comment by janegilring** [comment]
Could you try running the below command and check whether it returns a subscription where the DisplayName property matches the name of the subscription you are specifying in the -ResourceName parameter for the command which failed?

`AzureADPreview\Get-AzureADMSPrivilegedResource -Provider azureResources -Filter "Type eq 'subscription'"`

**Comment by bokkoman** [comment]
This is the result:

```
PS C:\Users\REDACTED> New-AzureADPIMRequest -RoleName 'Global Administrator'
No active Azure AD session, calling Connect-AzureAD (the login window often hides in the backgroud, minimize the PowerShell window to check if you do not see it)

Account                                            Environment TenantId                             TenantDomain
-------                                            ----------- --------                             ------------
REDACTED-Admin@REDACTED.onmicrosoft.com AzureCloud  c7caREDACTEDf85ac c7ca8REDACTED-4b...

ResourceId       : c7caREDACTED0f85ac
RoleDefinitionId : 62e90394-69f5-4237-9190-012177145e10
SubjectId        : 16a2b1c8-d445-4cc7-acd2-252511679954
Type             : UserAdd
AssignmentState  : Active
Schedule         : class AzureADMSPrivilegedSchedule {
                     StartDateTime: 2-2-2023 06:23:15
                     EndDateTime: 2-2-2023 14:23:08
                     Type: Once
                     Duration: PT0S
                   }

Reason           : Daily PIM elevation

PIM elevation for user REDACTED-Admin@REDACTED.onmicrosoft.com succeeded


PS C:\Users\REDACTED> AzureADPreview\Get-AzureADMSPrivilegedResource -Provider azureResources -Filter "Type eq 'subscription'"
PS C:\Users\REDACTED>
```

These are my Azure AD roles:
![image](https://user-images.githubusercontent.com/7511367/216248367-cf11049c-4f01-412c-8179-555cdd3f5e56.png)

And these are my azure resources:
![image](https://user-images.githubusercontent.com/7511367/216248591-4ed497b9-f6e5-4fc7-8b31-be3212ecbae9.png)


My end goal is to auto activate `Global Administrator` and the resource `Owner`.

**Comment by janegilring** [comment]
I see, thanks for the additional information.

I am puzzled with regard to why the following does not return the same information as seen in the portal:
`AzureADPreview\Get-AzureADMSPrivilegedResource` -Provider azureResources -Filter "Type eq 'subscription'"`

That is something outside of the PIMTools module I believe, although there could have been a better error message.

Since the AzureADPreview-module is deprecated and will stop working when Microsoft shuts down the ADAL APIs, I would rather look into using the new Microsoft Graph modules.

I am not sure whether it is worth investing time in getting PIMTools updated, as there is an existing module which does the same and is leveraging the Graph APIs:
https://github.com/JustinGrote/JAz.PIM

Maybe you could give that one a try and see if it works via MS Graph?

**Comment by bokkoman** [comment]
Thank you! This tool you mentioned works perfect for what I need 😄
